In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import plotly.express as px
import platform
import numpy as np
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objects as go
import plotly.express as px
import requests
from folium import plugins
import plotly.express as px

# 운영체제별 한글 폰트 설정
if platform.system() == 'Darwin': # Mac 환경 폰트 설정
    plt.rc('font', family='AppleGothic')
elif platform.system() == 'Windows': # Windows 환경 폰트 설정
    plt.rc('font', family='Malgun Gothic')

plt.rc('axes', unicode_minus=False) # 마이너스 폰트 설정


# 글씨 선명하게 출력하는 설정
%config InlineBackend.figure_format = 'retina'


# Warning 제거
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) 
warnings.simplefilter(action='ignore', category=UserWarning)  
pd.set_option('mode.chained_assignment',  None)   
#pd.set_option('mode.chained_assignment', 'warn')

In [5]:
# 판다스 출력 default 60 20
pd.options.display.max_rows = 60
pd.options.display.max_columns = 30

In [6]:
camping = pd.DataFrame()

years = ['2020','2021','2022']
month = ['01','02','03','04','05','06','07','08','09','10','11','12']
for year in years:
    try:
        for j in month:
            df = pd.read_excel(f'C:/Users/kjk42/Documents/python/Done/data/data_lab/{year}{j}.xlsx')
            df['date'] = year+j
            df = df[df['소분류 카테고리'] =='캠핑']
            camping = pd.concat([camping,df])
    except:
        pass
    
df = pd.read_excel(f'C:/Users/kjk42/Documents/python/Done/data/data_lab/201911.xlsx')
df['date'] = '201911'
df = df[df['소분류 카테고리'] =='캠핑']
camping = pd.concat([camping,df])

df = pd.read_excel(f'C:/Users/kjk42/Documents/python/Done/data/data_lab/201912.xlsx')
df['date'] = '201912'
df = df[df['소분류 카테고리'] =='캠핑']
camping = pd.concat([camping,df])

camping = camping.drop(labels=['순위','중분류 카테고리','소분류 카테고리'],axis=1).reset_index(drop=True)
camping.to_csv('datalab.csv')

In [7]:
camping = camping.sort_values(by='date').reset_index(drop=True)

In [12]:
camping['month']=camping.loc[:,'date'].apply(lambda x: x[-2:])

In [17]:
df = pd.read_csv(r'C:\Users\kjk42\Documents\python\Done\data\전국 캠핑장 위치 및 부가정보.csv')

In [18]:
df_id = df[['CMPSI_NM','CMPSI_SCTIN_NM','CMPSI_LTTD_VAL','CMPSI_LNGTD_VAL']]

In [19]:
camping.head(3)

              관광지명  광역시/도 시/군/구                   도로명주소  검색건수    date month
0          함허동천야영장  인천광역시   강화군  인천 강화군 해안남로1196번길 38-0  1078  201911    11
1  황산문화체육공원국민여가캠핑장   경상남도   양산시       경남 양산시 낙동로 295-19  1079  201911    11
2           중랑숲캠핑장  서울특별시   중랑구     서울 중랑구 망우로87길 110-0  1086  201911    11

In [20]:
camp_sum = camping.groupby(['관광지명','도로명주소'],as_index=False).agg(검색건수=('검색건수','sum'))

In [1]:
# import googlemaps

# my_key =
# maps = googlemaps.Client(key=my_key)  # my key값 입력
# lat = []  #위도
# lng = []  #경도

# places = list(camping['도로명주소'])

# for place in places:   
#     i = i + 1
#     try:
#         geo_location = maps.geocode(place)[0].get('geometry')
#         lat.append(geo_location['location']['lat'])
#         lng.append(geo_location['location']['lng'])
        

#     except:
#         lat.append('')
#         lng.append('')

# df = pd.DataFrame({'도로명주소':places, 'lat':lat, 'lon':lng})
# df.to_csv('camp_location_1.csv')

In [21]:
loc = pd.read_csv(r'C:\Users\kjk42\Documents\python\Done\data\camp_location_1.csv')

In [22]:
loc = loc.drop(labels='Unnamed: 0',axis=1)
loc

                       관광지명        lat         lon
0    경기 포천시 포천로2811번길 178-0  37.993553  127.157378
1        경북 칠곡군 학하4길 57-105  36.095306  128.485739
2                    경남 함안군  35.272559  128.406480
3                    서울 강동구  37.530125  127.123762
4       강원 평창군 이승복생가길 160-0  37.712629  128.480493
..                      ...        ...         ...
123       충북 괴산군 화양로 733-38  36.683324  127.806347
124     경남 합천군 황매산공원길 331-0  35.485037  127.997716
125       경남 양산시 낙동로 295-19  35.305996  128.983451
126  경기 양주시 만송로366번길 215-29  37.784568  127.099729
127      강원 평창군 흥정계곡4길 91-0  37.651819  128.313736

[128 rows x 3 columns]

In [28]:
df_id['CMPSI_LTTD_VAL'] = df_id['CMPSI_LTTD_VAL'].round(2)
df_id['CMPSI_LNGTD_VAL'] = df_id['CMPSI_LNGTD_VAL'].round(2)

In [31]:
df = df.drop(labels=['사업장명','CMPSI_LTTD_VAL','CMPSI_LNGTD_VAL'],axis=1)

In [32]:
df

,CMPSI_NM,CMPSI_SCTIN_NM,소재지전체주소,상세영업상태명,lat,lon
0,(주)디노담양힐링파크 지점,"일반야영장,카라반,글램핑",전라남도 담양군 봉산면 기곡리 836-2번지,영업중,35.27,126.96
1,(주)쉐르빌리안티티,글램핑,강원도 홍천군 서면 모곡리 491-46번지,영업중,37.70,127.60
2,(주)쉐르빌리안티티,글램핑,강원도 홍천군 서면 모곡리 547번지,영업중,37.70,127.60
3,(주)아웃오브파크,카라반,강원도 춘천시 남면 관천리 383,영업중,37.73,127.51
4,(주)아웃오브파크,카라반,강원도 춘천시 남면 관천리 356-12,영업중,37.73,127.51
...,...,...,...,...,...,...
3450,트리하우스계곡야영장,일반야영장,강원도 홍천군 내촌면 와야리 산 75,영업중,37.82,128.15
3451,성보촌 캠핑장,일반야영장,경상북도 문경시 호계면 호계리 23,영업중,36.65,128.19
3452,더 노은로 캠핑장,일반야영장,대전광역시 유성구 노은동 288-17,휴업,36.36,127.32
3453,청풍호반 오토캠핑장,자동차야영장,충청북도 제천시 청풍면 용곡리 976,영업중,36.98,128.12
3454,우리집 야영장,일반야영장,경상북도 군위군 소보면 서경리 311-3,폐업,36.23,128.50

In [33]:
addrs = list(set(df['CMPSI_NM']))
kakao_score=[]
kakao_name = []
header = {
    'User-Agent' : 'Mozila/5.0',
    'referer': 'https://map.kakao.com/'
}
for addr in addrs:
    
    response = requests.get(f'https://search.map.kakao.com/mapsearch/map.daum?callback=jQuery18109007274728495254_1669945532138&q={addr}&msFlag=S&page=1&sort=0',headers=header)
    html = response.text
    start_score=html.find('rating_average')
    end_score=html.find('rating_count')
    if start_score == -1:
        kakao_score.append('None')
        kakao_name.append(addr)
    else:
        kakao_score.append(html[start_score+16:end_score-2])
        kakao_name.append(addr)

kakao = pd.DataFrame()
kakao['CMPSI_NM'] = kakao_name
kakao['kakao_score'] = kakao_score